_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 'checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_10shot/model_final.pth'
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 80
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_10shot',)
  TEST: ('coco_trainval_generate', )

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (1000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 10

TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 500
OUTPUT_DIR: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_10shot"